---
- name: Ansible-Python Lab2
  hosts: labs
  tasks:
    - name: Remove Package
      yum:
        name: "{{ packages }}"
        state: absent
    # Local User setting
    - name: local user adding
      user:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ users }}"
      when: users is defined
    # cloud instance hostname setting
    - name: cloud instance hostname preserve
      lineinfile:
        path: /etc/cloud/cloud.cfg
        line: "preserve_hostname: true"
        state: absent

#    - debug:
#        msg: "{{ dummy }}"
  
